### ISSUE TITLE
Build fails on i686

### ISSUE THREAD

**Issue by igor-raits** [shepmaster/jetscii#34]
```rust
BUILDSTDERR: error[E0432]: unresolved import `std::arch::x86_64`
BUILDSTDERR:  --> src/simd.rs:6:11
BUILDSTDERR:   |
BUILDSTDERR: 6 |     arch::x86_64::{
BUILDSTDERR:   |           ^^^^^^ could not find `x86_64` in `arch`
```

**Comment by igor-raits** [comment]
I believe it is because `#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]` is wrong, on x86 you don't get arch::x86_64.

**Comment by shepmaster** [comment]
That's totally believable. I wonder if there's a way to easily test x86 in Travis (or other CI).

Since you have an x86 system on hand, would it be easy for you to patch the crate to use the correct imports?

**Comment by igor-raits** [comment]
I think people just use cross-compilation in travis. Probably check what ripgrep / regex and such. Or libc.

Going to patch it out now.

**Comment by igor-raits** [comment]
@shepmaster ok, #35 it is :)
