### ISSUE TITLE
Publishing the new version to crates.io

### ISSUE THREAD

**Issue by teovoinea** [shepmaster/jetscii#43]
The version currently on crates.io (0.4.4) is broken with the new version of rust that recently came out (1.54).

Version [0.5.0](https://crates.io/crates/jetscii/0.4.4) that you already created does work with the new version of rust.

Could you please publish the new version to crates.io?

**Comment by shepmaster** [comment]
Crates.io says [I published it a few months ago](https://crates.io/crates/jetscii/0.5.0) — am I missing something?

**Comment by teovoinea** [comment]
That's super odd, not sure why I didn't see that the first time around. Sorry about that!
