### ISSUE TITLE
potential segfault when using find

### ISSUE THREAD

**Issue by martony38** [shepmaster/jetscii#44]
I have a program that generate a word document from a json payload (cannot share/private repo).
That program segfaults about ~1-2% of the time.

I have traced the segfault to the `find` method from `jetscii::Bytes` in 1 of the dependency https://github.com/PoiScript/strong-xml/blob/db2306cdb62b1ea5d020575ed9d7ee0318e09e17/strong-xml/src/xml_escape.rs#L12.

Here are 2 example values I was able to print of the `raw` variable before the segfault happened: 
- "Claims Liability"
- "Total Net Claims"

## environment
MacOS 10.15.7
rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Comment by shepmaster** [comment]
This is a very unfortunate bug report. I'd like to take it with maximum importance, but there's _nothing for me to go on_. This crate already attempts to do a [_wide_ range of tests](https://github.com/shepmaster/jetscii/blob/master/src/simd.rs#L293) to exercise edge conditions.
