### ISSUE TITLE
Investigate substring search

### ISSUE THREAD

**Issue by shepmaster** [shepmaster/jetscii#7]
@bluss mentioned starting some work, so I figured we might as well create a little issue to track things.

Off the top of my head, I was thinking that we could use the same instruction, but set the "IMM8 Control Register" to `Equal ordered (substring search)` mode (binary `11`). Then we could load the first 16 bytes of the needle into the search register, and iterate through memory just like the existing code. Needs to handle the strange alignment gyrations.

If the needle is < (or <= ?) 16 bytes, a match would be a success. If it's longer, we'd have to fall back to a slower `memcmp` type check.

Potentially could use any of the advanced substring logic as well (Boyer Moore?).

Let me know if I can help shed any light on the assembly bits!

**Comment by shepmaster** [comment]
Implemented an initial version of this in [v0.3.0](https://github.com/shepmaster/jetscii/tree/v0.3.0)

**Comment by bluss** [comment]
exciting!

**Comment by bluss** [comment]
It's basically the world's fastest O(n²) string search. :smile: 

Not completely unlike my own trials, which haven't progressed much lately.
